goodWords = {
        "amo você",
        "gosto de você",
        "você é incrível",
        "você é muito especial",
        "parabéns",
        "tenho orgulho de você",
        "você é importante pra mim",
        "você é demais",
        "fico feliz por você existir",
        "você ilumina meu dia",
        "confio em você",
        "estou aqui por você",
        "você consegue",
        "muito bem",
        "acredito em você",
        "você é forte",
        "você é inteligente",
        "você é única",
        "você merece coisas boas",
        "que orgulho de você",
        "você é maravilhoso"
    }

badWords = {
        "eu te odeio",
        "você é chata",
        "você é irritante",
        "você é inútil",
        "que decepção",
        "ninguém gosta de você",
        "você é insuportável",
        "cala a boca",
        "vai embora",
        "você estraga tudo",
        "que vergonha",
        "isso foi ridículo",
        "você é péssima",
        "não aguento você",
        "você só faz besteira",
        "você só faz merda",
        "que fracasso",
        "você é incompetente",
        "isso foi horrível",
        "que coisa idiota",
        "você é idiota",
        "você é um desastre"
    }